#!/bin/bash
set -e
set -x
source /srv/zulip-venv/bin/activate
export PATH=$PATH:/srv/zulip-venv/bin
./tools/test-js-with-node cover
coverage run --omit='*/zulip-venv-cache/*' ./tools/test-js-with-casper
cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
